version: "3.9"

services:
  web:
    image: php:8.2-apache
    container_name: webshop_php
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    image: mariadb:11
    container_name: webshop_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webshop
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
